name = 'Sunline'
license = 'MIT'
licenselink = 'https://github.com/sundegan/Sunline/blob/main/LICENSE'
description = 'A minimal and modern Hugo theme built with Tailwind CSS.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/sundegan/Sunline'

# If you have a running demo of the theme
demosite = 'https://sundegan.cn'

# Taxonomy terms
tags = ['minimal', 'modern', 'tailwindcss', 'blog']
features = ['responsive design', 'dark mode', 'article search', 'gallery', 'comment section integration']

# If the theme has a single author
[author]
  name = 'Degan Sun'
  homepage = 'https://sundegan.cn'